name: rain_check
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.2.0
  math_expressions: ^2.4.0
  cupertino_icons: ^1.0.8
  auto_route: ^10.2.0
  json_annotation: ^4.9.0
  freezed: ^3.2.3
  gap: ^3.0.1
  flutter_bloc: ^9.1.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  json_serializable: ^6.11.2
  pinput: ^6.0.1
  google_sign_in: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter_gen: ^5.12.0
  responsive_framework: ^1.5.1
  flutter_icon_snackbar: ^1.2.1
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  intl_phone_field: ^3.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.6
  flutter_lints: ^5.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_flavorizr: ^2.4.1

# FlutterGen Configuration
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: false
  fonts:
    enabled: true
  assets:
    enabled: true

# Flutter Configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/logo.png
    - assets/images/logo-blue.png
    - assets/images/google.png
    - assets/data/ppc_boundaries.geojson
    - assets/data/ppc_flooding_area.geojson

  # Fonts
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

# Flutter Launcher Icons (only ONE section, at root)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-blue.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo-blue.png"

  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true